### ISSUE TITLE
Moving grammar to the official grammars repository?

### ISSUE THREAD

**Issue by KvanTTT** [federicobond/solidity-antlr4#14]
Would you like to join us? ;) https://github.com/antlr/grammars-v4

**Comment by federicobond** [comment]
Yes! I was waiting to stabilize the grammar but I think it's ready now. Language is still evolving though, should I treat this as bleeding edge and merge back changes to the official repo?

**Comment by KvanTTT** [comment]
It would be better to improve grammar directly in the official repository fork if it's not difficult for you.
