### ISSUE TITLE
Support ~ as the version operator.

### ISSUE THREAD

**Issue by LogvinovLeon** [federicobond/solidity-antlr4#15]
Currently solidity-parser-antlr is unable to parse `pragma solidity ~0.4.10`, because `~` isn't listed as a version operator in this repo. 
Please check out, that tilda-ranges are as valid as carret-ranges https://docs.npmjs.com/misc/semver#tilde-ranges-123-12-1

**Comment by federicobond** [comment]
Thank you for reporting this @LogvinovLeon! I have a fix in b3f64a5e and will release a new JS parser shortly.

**Comment by LogvinovLeon** [comment]
Also - what's the current situation with this grammar/parser vs solidity-parser? Looks like you're maintaining both. Which one is prefrable/deprecated? I've choosen this one for better API (really live the visit functionality) and speed.

**Comment by federicobond** [comment]
solidity-parser is no longer receiving any updates. There have been some talks about replacing it with the antlr version but I haven’t got time to work on it yet.
