### ISSUE TITLE
Relicense project to MIT

### ISSUE THREAD

**Issue by federicobond** [federicobond/solidity-antlr4#16]
Pinging @domainexpert and @frangio. Several people have approached me in the past with the intention of building tools with a more permissive license on top of this code. I would like to get your opinions or consent as collaborators to relicense this project to MIT.

Let me know if any of you disagrees or state your consent explicitly. Thank you in advance!

**Comment by frangio** [comment]
I'm okay with relicensing to MIT. 👍

**Comment by federicobond** [comment]
Project relicensed to MIT. Changes done without explicit consent to the new license were not deemed original enough. Thank you all!

**Comment by sam-steffen** [comment]
Can you also update the header comment in `Solidity.g4` to match MIT license?

**Comment by federicobond** [comment]
Done. Thanks for noticing it.
