### ISSUE TITLE
Listening for `functionCall`?

### ISSUE THREAD

**Issue by fvictorio** [federicobond/solidity-antlr4#17]
Hi, I don't know much about ANTLR so sorry in advance if this doesn't make sense.

I want to add a Listener for `functionCall`, but those nodes are interpreted as `expression`s instead. I guess this happens because one of the rules for `expression` (the [fourth one](https://github.com/solidityj/solidity-antlr4/blob/06a9d0ffb3ac66de945e4832db36cc6aa05c9b3c/Solidity.g4#L231)) has the same definition as `functionCall` (and that rule is not inside `expression`). Maybe replacing that for `functionCall` will do the trick?

Thanks!

**Comment by fvictorio** [comment]
Ok, that doesn't work because it causes a `mutually left-recursive error`.

**Comment by federicobond** [comment]
Yes, there's a mutual left recursion error that I haven't found a workaround to. You can check the code at solidity-parser-antlr for how to handle the case.
