### ISSUE TITLE
Question: what is nameValueList ?

### ISSUE THREAD

**Issue by yxliang01** [federicobond/solidity-antlr4#18]
I am now trying to understand what the field `"names"` in a `functionCall` node is for. So, I realized it has something to do with `nameValueList` defined in this grammar at https://github.com/solidityj/solidity-antlr4/blob/edce5c44d2d681e32bb23034d822bf0fcf1cb43e/Solidity.g4#L265 . But, I don't think I have seen this function call syntax or maybe I understood this grammar wrongly. Would be great if anyone can explain this.

Thanks

**Comment by federicobond** [comment]
Hi @yxliang01 this is related to Solidity support for named function arguments. See here: https://solidity.readthedocs.io/en/v0.4.21/control-structures.html?highlight=named%20arguments#named-calls-and-anonymous-function-parameters

**Comment by yxliang01** [comment]
I see. I didn't notice this new Solidity feature. Thanks!

**Comment by federicobond** [comment]
It's a pretty old feature, it just hasn't gathered much usage.
