### ISSUE TITLE
Solidity type information is not supported

### ISSUE THREAD

**Issue by hai-ko** [federicobond/solidity-antlr4#20]
It seems that the solidity [type information](https://solidity.readthedocs.io/en/v0.5.10/units-and-global-variables.html?highlight=.creationCode#type-information) are not supported. If I have a contract containing e.g. `type(Proxy).creationCode;` it will fail with `extraneous input 'type' expecting`.

**Comment by federicobond** [comment]
Thank you for reporting. Closed in https://github.com/solidityj/solidity-antlr4/commit/b7065ca7a2d00662b345f2fdd2940d00d51ad30d.
